### ISSUE TITLE
 The Song loader is only active for a min

### ISSUE THREAD

**Issue by KeMpeRr** [xyonico/BeatSaberSongLoader#13]
https://github.com/Umbranoxio/BeatSaberModInstaller/issues/15 

> I start the game and I can play one map before beat saber reverts to an un-modded capacity. The little in game beat-saver button that took you to the map download screen is not there anymore. Basically, i can only play maps I have already downloaded and I can only play one unless i want to restart the game over and over again to load the list again.

**Comment by shutovilya** [comment]
Same problem, there are only default tracks in the menu after any played game.
No stats are saved too, because game thinks you played "100 dollar bills" - the first default track.

**Comment by lupinewolf** [comment]
Same deal here

**Comment by xyonico** [comment]
This only happens if you have outdated plugin installed as well. You'll want to do a clean install, delete the Plugins folder to get rid of all your old plugins (you won't need those old versions again) and run the mod installer again or install manually if you want.

**Comment by shutovilya** [comment]
clean install without any other plugins worked
