### ISSUE TITLE
Beat saber mod v 4.1

### ISSUE THREAD

**Issue by tyryno65** [xyonico/BeatSaberSongLoader#15]
The mod seems to have interrupted the earlier patch on wrong bpms for Rasputin by the jadas. it seems to be that only this song was affected by this patch.

**Comment by xyonico** [comment]
v4.2 will have a fix for the wrong BPM issue. It will be released in a few hours from now.
I'll close this issue when that comes out.

**Comment by xyonico** [comment]
v4.2 fixes this issue.
