### ISSUE TITLE
My custom songs have vanished!

### ISSUE THREAD

**Issue by LillyHill** [xyonico/BeatSaberSongLoader#16]
Hi! 
When I played beatsaber the other day, all my custom songs just vanished!
I have tried everything, uninstalled beatsaber installed it again removed mod and reinstalled mod nothing works!
What can be wrong?

**Comment by Qu4Z** [comment]
Have you updated to the latest version of the plugin? If you download the "AlreadyInstalled" version from https://github.com/xyonico/BeatSaberSongLoader/releases, copy the files into the Beat Saber folder (under Steam\steamapps\common\Beat Saber or similar), then drag the Beat Saber.exe file onto IPA.exe (not the folder), it should update you to the latest plugin. 

If you launch Beat Saber after this, your custom songs should appear (although you may need to give it a few moments to load your library if you have a lot of songs). 

For more information see the ReadMe. Note that there appear to be a few things broken in 4.2 (Fractional BPM, Difficulty), but earlier versions unfortunately aren't compatible with the latest Beat Saber update that just dropped recently. 

Good luck!

EDIT: Although I see a notice that it was patched shortly after initial release to fix Note Speed, so the BPM issue might not occur for you. I don't have time to play now (sadly), but I'll test a few things later today.

**Comment by xyonico** [comment]
Try deleting your Plugins folder and running this mod installer: https://github.com/Umbranoxio/BeatSaberModInstaller/releases

**Comment by LillyHill** [comment]
Thanks so much now it's working again!:)
