### ISSUE TITLE
Custom songs dont reload after playing once

### ISSUE THREAD

**Issue by R0CKB0TT0M** [xyonico/BeatSaberSongLoader#19]
when I start the game everything works fine but after playing a custom song and failing or finishing it on the replay screen it says im playing 100$ bills and when I press menu all the custom songs are gone. The only way to get them back that I could find was to restart the game. But this has to be done after every playthrough of a custom song so not really a solution.
I have beatsaber version 0.11.1 (updated an hour ago acording to oculus)
and I installed the latest version of BeatSaberSongLoader first using the Mod installer and after that didnt work I also tried manualy.
just tried again using newly released version 4.2.2 of BeatSaberSongLoader, problem still persists.

**Comment by xyonico** [comment]
This happens if you have outdated plugins still installed in your Plugins folder. To fix this, delete the Plugins folder and run the mod installer again.

**Comment by StealthOrc** [comment]
Same here - This might also bei interesting but I think this is just the result of the songs vanishing / bugging out: the custom songs just vanish but i found out that I can search an empty string and that I then get all songs but all the custom songs are bugged out, they dont preview the song and if I start them they instantly exit out and show the result screen.
