### ISSUE TITLE
Can't use menu after installing

### ISSUE THREAD

**Issue by JoramUiterwijk** [xyonico/BeatSaberSongLoader#20]
As soon as I install the SongLoader plugin, the pointer dissapears and I'm unable to use the menu. So I can't do anything. Is there a fix for this?

**Comment by xyonico** [comment]
We've figured out that this bug happens to those that are still on the old version of Beat Saber. Song Loader Plugin v4.0 and later only work on Beat Saber version 0.11.0 and later.
Either you haven't updated the game on Steam/Oculus Store or you don't have a legitimate copy of the game.
