### ISSUE TITLE
Special symbols in song path like '#' makes the song assets inaccessible

### ISSUE THREAD

**Issue by xyonico** [xyonico/BeatSaberSongLoader#6]
URL encoding the file path may fix it, since I'm using the WWW class to read a local file.

**Comment by SagsMug** [comment]
I fixed it in unrelated pull request by using Uri with AbsoluteUri as the methods in HttpUtility with path encoding didn't work
Its in #9

**Comment by xyonico** [comment]
Fixed in refactoring branch.
